#
---
puppet-syntax:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake syntax
puppet-lint:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake lint
puppet-metadata:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake metadata
unit-test-ruby-2.1:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake spec
unit-test-ruby-2.2:
  stage: test
  tags:
    - docker
  image: ruby:2.2
  allow_failure: true
  script:
    - bundle install
    - bundle exec rake spec
unit-test-ruby-2.3:
  stage: test
  tags:
    - docker
  image: ruby:2.3
  script:
    - bundle install
    - bundle exec rake spec
acceptance-test-puppet-agent-4.7.1:
  stage: test
  cache:
    paths:
      - vendor
  tags:
    - beaker
  script:
    - export PUPPET_INSTALL_TYPE=agent
    - export PUPPET_INSTALL_VERSION=1.7.2
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake acceptance
acceptance-test-puppet-agent-4.9.3:
  stage: test
  cache:
    paths:
      - vendor
  allow_failure: true
  tags:
    - beaker
  script:
    - export PUPPET_INSTALL_TYPE=agent
    - export PUPPET_INSTALL_VERSION=1.9.2
    - bundle install --no-binstubs --path=vendor
    - bundle exec rake acceptance
